### ISSUE TITLE
add and generate crd documentaion

### ISSUE THREAD

**Issue by mzeevi** [sahar2339/namespaceLabel#3]
Add documentation to the CRD itself.

Also, CRDs should be documented on GitHub for easier external usage.

You may use the following project to achieve that: https://github.com/elastic/crd-ref-docs

**Comment by sahar2339** [comment]
@mzeevi 
It's come to my mind that I am stupid because I use centos9 VM and it's not compatible with the crd script.
can we maybe return to it later?
